### ISSUE TITLE
Issues to solve

### ISSUE THREAD

**Issue by igunduz** [BIMSBbioinfo/multiomics_vs_panelseq#4]
## Github Repo Instructions

- [x] 1.  If user wants to run beatAML and runs this comment : `Rscript src/model_DR.R beatAML ./data ./results 1 10` this error returns: 

#TODO add this line to clarify `bash get_data.sh -o ./`
```
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './data/prepared/data_beatAML.RDS', probable reason 'No such file or directory'
Execution halted
```

- [ ] 2. Code returns this x per drug after running the script due to lapplu  operations

```
[[1]]
NULL
```

- [x] 3.  Check for missing packages, install if needed for collate_figures_tables.R

- [x] 4. Run the code for beatAML and PDX without error

## Figures 

- [x] 1.  Fix Rsquare as Rsquared from the figures
- [x] 2. Add a metric for multiomics improvement in figure 2
- [x] 3. Change the feature type indicator place (it's in the middle of the plot) **figure_S2.**
- [x] 4. Add a theme for **figure_S1**. It's hard to distinguish there is a result for PCA initially
- [x] 5. Improvement metric is also missing for **figure_S2.**
- [x] 6.  Re-arrange the layers for **figure_S2.**. It's a little bit skewed to the right side
- [x] 7. Merge figure 1 and figure 2
- [x] 8. figure_S1 Split the figure in half (top/bottom) and clearly show that one result (top row) is without PCA and the other one (bottom row) is with PCA and label them (A/B) 
- [x] 9. Make an additional figure as in main Figure 1D (PDX), one panel for glmnet results for PDX and one panel for svm results for PDX (again label them C and D)

**Comment by borauyar** [comment]
Yes, it should work if `get_data.sh` has already run.
